global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'db_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['db-service:8080']
        labels:
          application: 'DB Service Application'
  - job_name: 'query_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['query-service:8080']
        labels:
          application: 'Query Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'
